[tool.poetry]
name = "package-a"
version = "0.1.0"
description = "Package A"
authors = ["John doe <john.doe@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
