[tool.poetry]
name = "app"
version = "0.1.0"
description = "App"
authors = ["John doe <john.doe@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
package-b = {path = "../package-b", develop = true}

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
